---
database:
  driverClass: com.mysql.jdbc.Driver
  password: ~
  properties:
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.hbm2ddl.auto: update
  url: "jdbc:mysql://localhost:3306/test2"
  user: root
  password: root
logging:
  level: INFO
  loggers:
    iou: DEBUG
server:
  applicationConnectors:
    -
      port: 50012
      type: http
  adminConnectors:
    -
      port: 50011
      type: http